name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Instalar deps
        run: pnpm install --frozen-lockfile

      # opcional, se tiver script de lint
      - name: Lint
        run: pnpm run lint
        continue-on-error: false

      # opcional, se tiver testes
      - name: Test
        run: pnpm test -- --ci

      - name: Build
        run: pnpm build
